
import { UserProfile } from '@/lib/supabase';

export const createMockUserProfile = (overrides: Partial<UserProfile> = {}): UserProfile => {
  return {
    id: 'test-user-id',
    email: 'test@example.com',
    name: 'Test User',
    role_id: 'test-role-id',
    user_roles: {
      id: 'test-role-id', 
      name: 'member'
    },
    avatar_url: null,
    company_name: 'Test Company',
    industry: 'Technology',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    phone: null,
    instagram: null,
    linkedin: null,
    country: null,
    state: null,
    city: null,
    company_website: null,
    current_position: null,
    company_sector: null,
    company_size: null,
    annual_revenue: null,
    primary_goal: null,
    business_challenges: null,
    ai_knowledge_level: null,
    weekly_availability: null,
    networking_interests: null,
    nps_score: null,
    phone_country_code: '+55',
    onboarding_completed: true,
    onboarding_completed_at: '2024-01-01T00:00:00Z',
    is_premium: false,
    premium_expires_at: null,
    referred_by: null,
    referrals_count: 0,
    successful_referrals_count: 0,
    last_login_at: null,
    login_count: 0,
    email_verified: false,
    email_verified_at: null,
    profile_completion_percentage: 0,
    last_profile_update: null,
    preferences: null,
    timezone: null,
    language: 'pt',
    notifications_enabled: true,
    marketing_emails_enabled: true,
    role: null,
    ...overrides,
  };
};
