-- Simplificar schema removendo campos duplicados
-- Manter apenas os 5 objetos principais unificados

-- Remover colunas duplicadas da tabela onboarding_final 
-- (mantendo apenas os campos JSONB estruturados)
ALTER TABLE public.onboarding_final 
DROP COLUMN IF EXISTS name,
DROP COLUMN IF EXISTS email,
DROP COLUMN IF EXISTS phone,
DROP COLUMN IF EXISTS instagram,
DROP COLUMN IF EXISTS linkedin,
DROP COLUMN IF EXISTS state,
DROP COLUMN IF EXISTS city,
DROP COLUMN IF EXISTS birth_date,
DROP COLUMN IF EXISTS curiosity,
DROP COLUMN IF EXISTS profile_picture,
DROP COLUMN IF EXISTS company_name,
DROP COLUMN IF EXISTS company_website,
DROP COLUMN IF EXISTS business_sector,
DROP COLUMN IF EXISTS company_size,
DROP COLUMN IF EXISTS annual_revenue,
DROP COLUMN IF EXISTS position,
DROP COLUMN IF EXISTS has_implemented_ai,
DROP COLUMN IF EXISTS ai_tools_used,
DROP COLUMN IF EXISTS ai_knowledge_level,
DROP COLUMN IF EXISTS daily_tools,
DROP COLUMN IF EXISTS who_will_implement,
DROP COLUMN IF EXISTS ai_implementation_objective,
DROP COLUMN IF EXISTS ai_implementation_urgency,
DROP COLUMN IF EXISTS ai_main_challenge,
DROP COLUMN IF EXISTS main_objective,
DROP COLUMN IF EXISTS area_to_impact,
DROP COLUMN IF EXISTS expected_result_90_days,
DROP COLUMN IF EXISTS urgency_level,
DROP COLUMN IF EXISTS success_metric,
DROP COLUMN IF EXISTS main_obstacle,
DROP COLUMN IF EXISTS preferred_support,
DROP COLUMN IF EXISTS ai_implementation_budget,
DROP COLUMN IF EXISTS weekly_learning_time,
DROP COLUMN IF EXISTS content_preference,
DROP COLUMN IF EXISTS content_frequency,
DROP COLUMN IF EXISTS wants_networking,
DROP COLUMN IF EXISTS community_interaction_style,
DROP COLUMN IF EXISTS preferred_communication_channel,
DROP COLUMN IF EXISTS follow_up_type,
DROP COLUMN IF EXISTS learning_motivators,
DROP COLUMN IF EXISTS best_days,
DROP COLUMN IF EXISTS best_periods,
DROP COLUMN IF EXISTS accepts_case_study,
DROP COLUMN IF EXISTS country,
DROP COLUMN IF EXISTS timezone,
DROP COLUMN IF EXISTS motivation_sharing;